# Generated by Django 5.2.3 on 2025-06-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_review_reviewphoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyphoto",
            name="caption",
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.property"
            ),
        ),
    ]
