# Generated by Django 5.2.3 on 2025-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_propertyphoto_caption_propertyphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyphoto',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.CharField(choices=[('comfort', 'Комфорт / Комфорт'), ('business', 'Business / Бизнес'), ('luxury', 'Luxury / Премиум')], default='comfort', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Свободна', 'Available / Свободна'), ('Забронирована', 'Booked / Забронирована'), ('Занята', 'Occupied / Занята'), ('На обслуживании', 'Maintenance / На обслуживании')], default='Свободна', max_length=20),
        ),
    ]
