# Generated by Django 5.2.3 on 2025-09-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="Время заезда"),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="Время выезда"),
                ),
                ("start_date", models.DateField(verbose_name="Дата заезда")),
                ("end_date", models.DateField(verbose_name="Дата выезда")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая стоимость"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("pending_payment", "Ожидает оплаты"),
                            ("payment_failed", "Ошибка оплаты"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "kaspi_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="ID платежа в системе Kaspi",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время истечения неоплаченного бронирования",
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="Время отмены бронирования", null=True
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("changed_plans", "Изменились планы"),
                            ("found_better", "Нашел лучший вариант"),
                            ("too_expensive", "Слишком дорого"),
                            ("owner_cancelled", "Отменено владельцем"),
                            ("payment_issues", "Проблемы с оплатой"),
                            ("wrong_dates", "Ошибка в датах"),
                            ("emergency", "Форс-мажор"),
                            ("no_response", "Нет ответа от владельца"),
                            ("other", "Другая причина"),
                        ],
                        help_text="Причина отмены",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cancel_reason_text",
                    models.TextField(
                        blank=True, help_text="Дополнительное описание причины отмены", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто отменил бронирование",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
    ]
