# Generated by Django 5.2.3 on 2025-08-07 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_kaspi_payment_id_alter_booking_status'),
        ('listings', '0007_fix_property_class_add_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('changed_plans', 'Изменились планы'), ('found_better', 'Нашел лучший вариант'), ('too_expensive', 'Слишком дорого'), ('owner_cancelled', 'Отменено владельцем'), ('payment_issues', 'Проблемы с оплатой'), ('wrong_dates', 'Ошибка в датах'), ('emergency', 'Форс-мажор'), ('no_response', 'Нет ответа от владельца'), ('other', 'Другая причина')], help_text='Причина отмены', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason_text',
            field=models.TextField(blank=True, help_text='Дополнительное описание причины отмены', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Время отмены бронирования', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Кто отменил бронирование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Время истечения неоплаченного бронирования', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kaspi_payment_id',
            field=models.CharField(blank=True, help_text='ID платежа в системе Kaspi', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.property', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('pending_payment', 'Ожидает оплаты'), ('payment_failed', 'Ошибка оплаты'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'start_date', 'end_date'], name='bookings_bo_propert_d79538_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_86acff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
    ]
