# Generated by Django 5.2.3 on 2025-09-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_code", "Просмотр кода доступа"),
                            ("send_code", "Отправка кода доступа"),
                            ("update_code", "Изменение кода доступа"),
                            ("view_phone", "Просмотр телефона"),
                            ("export_data", "Экспорт данных"),
                            ("view_payment", "Просмотр платежных данных"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_type", models.CharField(max_length=50)),
                ("object_id", models.IntegerField()),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("telegram_chat_id", models.CharField(blank=True, max_length=255, null=True)),
                ("whatsapp_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"], name="core_auditl_user_id_7b678c_idx"
                    ),
                    models.Index(
                        fields=["action", "timestamp"], name="core_auditl_action_096de0_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"], name="core_auditl_object__42e4a9_idx"
                    ),
                ],
            },
        ),
    ]
