version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "while true; do sleep 3600; done"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-booking_bot.settings}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-web,localhost,127.0.0.1}
      DEBUG: ${DEBUG:-1}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
