# Generated by Django 5.2.3 on 2025-09-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("super_admin", "Super Admin"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("telegram_state", models.JSONField(blank=True, default=dict)),
                ("whatsapp_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("whatsapp_state", models.JSONField(blank=True, default=dict)),
                (
                    "ko_factor",
                    models.FloatField(
                        default=0.0, help_text="Коэффициент отмен пользователя (0-1)"
                    ),
                ),
                (
                    "requires_prepayment",
                    models.BooleanField(
                        default=False, help_text="Требуется ли предоплата от этого пользователя"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "users_userprofile",
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id"], name="users_userp_telegra_36290a_idx"
                    ),
                    models.Index(fields=["user"], name="users_userp_user_id_d181df_idx"),
                ],
            },
        ),
    ]
