# Generated by Django 5.2.3 on 2025-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
