# Generated by Django 5.2.3 on 2025-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_ko_factor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ko_factor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='requires_prepayment',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Номер WhatsApp пользователя (без +)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_state',
            field=models.JSONField(blank=True, default=dict, help_text='Состояние WhatsApp бота для пользователя'),
        ),
    ]
