# Generated by Django 5.1.12 on 2025-10-28 06:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Создан, ожидает оплаты"),
                            ("processing", "В обработке"),
                            ("success", "Оплачен"),
                            ("failed", "Ошибка"),
                            ("refunded", "Возврат"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("kaspi", "Kaspi Pay"),
                            ("cash", "Наличные"),
                            ("card", "Банковская карта"),
                            ("transfer", "Банковский перевод"),
                            ("static_qr", "Статичный QR код"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="KZT", max_length=3)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Название платёжного провайдера",
                        max_length=50,
                    ),
                ),
                ("invoice_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF квитанция об оплате",
                        null=True,
                        upload_to="receipts/%Y/%m/%d/",
                    ),
                ),
                (
                    "receipt_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Сумма из квитанции",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "realtor_approval_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Не требуется"),
                            ("pending_approval", "Ожидает одобрения риелтора"),
                            ("approved", "Одобрено риелтором"),
                            ("rejected", "Отклонено риелтором"),
                        ],
                        default="not_required",
                        help_text="Статус одобрения риелтором",
                        max_length=20,
                    ),
                ),
                (
                    "realtor_comment",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий риелтора при одобрении/отклонении",
                    ),
                ),
                (
                    "realtor_decision_at",
                    models.DateTimeField(
                        blank=True, help_text="Когда риелтор принял решение", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finances.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёжная транзакция",
                "verbose_name_plural": "Платёжные транзакции",
                "ordering": ["-created_at"],
            },
        ),
    ]
