# Generated by Django 5.1.12 on 2025-10-28 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("properties", "0004_propertyaccessinfo_propertyaccesslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Оценка от 1 до 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "cleanliness_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Чистота",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Расположение",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "value_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Соотношение цена/качество",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "communication_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Качество связи с владельцем",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "accuracy_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Соответствие описанию",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "check_in_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Процесс заселения",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "realtor_response",
                    models.TextField(blank=True, help_text="Ответ владельца на отзыв"),
                ),
                (
                    "realtor_response_at",
                    models.DateTimeField(
                        blank=True, help_text="Дата ответа владельца", null=True
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, help_text="Одобрен модератором"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        help_text="Бронирование, к которому относится отзыв",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="bookings.booking",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Фотография", upload_to="reviews/photos/%Y/%m/%d/"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Подпись к фото", max_length=255
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Порядок отображения"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        help_text="Отзыв, к которому относится фото",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография отзыва",
                "verbose_name_plural": "Фотографии отзывов",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["property", "-created_at"],
                name="reviews_rev_propert_cab8b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="reviews_rev_user_id_a65d48_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rev_rating_2db6dd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "property", "booking")},
        ),
        migrations.AddIndex(
            model_name="reviewphoto",
            index=models.Index(
                fields=["review", "order"], name="reviews_rev_review__a35876_idx"
            ),
        ),
    ]
