# Generated by Django 5.1.12 on 2025-10-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("properties", "0004_propertyaccessinfo_propertyaccesslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, help_text="Время последнего сообщения", null=True
                    ),
                ),
                (
                    "last_message_preview",
                    models.CharField(
                        blank=True,
                        help_text="Превью последнего сообщения",
                        max_length=200,
                    ),
                ),
                (
                    "user1_unread_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество непрочитанных сообщений для user1",
                    ),
                ),
                (
                    "user2_unread_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество непрочитанных сообщений для user2",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Бронирование (если есть)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="bookings.booking",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        help_text="Объект недвижимости (если есть)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="properties.property",
                    ),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        help_text="Первый участник (обычно гость)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        help_text="Второй участник (обычно риелтор)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат-диалог",
                "verbose_name_plural": "Чат-диалоги",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Текст сообщения")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Прочитано получателем"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="Время прочтения", null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, help_text="Время отправки"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Диалог",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Отправитель",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user1", "-last_message_at"],
                name="chat_chatco_user1_i_0bfcc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user2", "-last_message_at"],
                name="chat_chatco_user2_i_21f71a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["property"], name="chat_chatco_propert_abcc7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["booking"], name="chat_chatco_booking_54ed5b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("user1", models.F("user2")), _negated=True),
                name="chat_conversation_different_users",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "sent_at"],
                name="chat_chatme_convers_7d639a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "-sent_at"], name="chat_chatme_sender__e24abf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "is_read"],
                name="chat_chatme_convers_499f50_idx",
            ),
        ),
    ]
